// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARtQ_BpPrZiUDPZruA8AdZXsSLNX02aKQ',
    appId: '1:878645308246:web:6cb3312f4a751cb9c8c4f7',
    messagingSenderId: '878645308246',
    projectId: 'myfrstapp-d5fad',
    authDomain: 'myfrstapp-d5fad.firebaseapp.com',
    storageBucket: 'myfrstapp-d5fad.appspot.com',
    measurementId: 'G-XHN494201J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy2Gvzqi6N8jjuFu6i_2HOny9pAtJHQ1I',
    appId: '1:878645308246:android:b05668c3b99e9054c8c4f7',
    messagingSenderId: '878645308246',
    projectId: 'myfrstapp-d5fad',
    storageBucket: 'myfrstapp-d5fad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACNnIzTCVC-61MxI2UIjdwImssjeRkEkk',
    appId: '1:878645308246:ios:f4455a1b1533de8ec8c4f7',
    messagingSenderId: '878645308246',
    projectId: 'myfrstapp-d5fad',
    storageBucket: 'myfrstapp-d5fad.appspot.com',
    iosBundleId: 'com.example.myfrstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACNnIzTCVC-61MxI2UIjdwImssjeRkEkk',
    appId: '1:878645308246:ios:e60ec368909b51c7c8c4f7',
    messagingSenderId: '878645308246',
    projectId: 'myfrstapp-d5fad',
    storageBucket: 'myfrstapp-d5fad.appspot.com',
    iosBundleId: 'com.example.myfrstapp.RunnerTests',
  );
}
